# Generated by Django 6.0 on 2025-12-17 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='productImages/')),
                ('device_type', models.CharField(choices=[('L', 'Laptop'), ('M', 'Mobile')], max_length=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('brochure', models.FileField(upload_to='productBrochures/')),
            ],
        ),
    ]
