# Generated by Django 6.0 on 2025-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product_media_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='media_choice',
            field=models.CharField(choices=[('Laptop', [('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')]), ('Mobile', [('android', 'Android'), ('ios', 'iOS')]), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Product Name'),
        ),
    ]
