# Generated by Django 6.0 on 2025-12-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='This is a description ', verbose_name='Description of Product'),
            preserve_default=False,
        ),
    ]
