# Generated by Django 6.0 on 2025-12-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='media_choice',
            new_name='os',
        ),
    ]
